spring:
  profiles:
    active: test

---
spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enable:d: true
  datasource:
    url: "jdbc:h2:mem:mydb"
    username: "sa"
    password: "password"
    driver-class-name: org.h2.Driver

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env, beans"


---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "password"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update


